version: '3'

services:
  app:
    image: docker-next-dev
    build: .
    deploy:
      replicas: 10
      resources:
        limits:
            cpus: "0.3"
            memory: 500M
      restart_policy:
        condition: on-failure
    ports:
      - 3000:3000
    volumes:
      - ./pages:/app/pages
      - ./public:/app/public
      - ./styles:/app/styles